ALTER TABLE school_users ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE school_users ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

CREATE TABLE account_deletion_requests (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 student_id BIGINT NOT NULL REFERENCES school_users(id),
 reason VARCHAR(2000) NOT NULL,
 status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
 requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
 reviewed_at TIMESTAMP WITH TIME ZONE,
 reviewed_by_id BIGINT REFERENCES school_users(id),
 review_reason VARCHAR(2000)
);
CREATE INDEX idx_deletion_student_status ON account_deletion_requests(student_id, status);
CREATE INDEX idx_deletion_status_date ON account_deletion_requests(status, requested_at);
