ALTER TABLE schools ADD COLUMN cep VARCHAR(8);
ALTER TABLE schools ADD COLUMN uf VARCHAR(2);
CREATE INDEX idx_schools_cep ON schools(cep);
CREATE INDEX idx_schools_city_uf ON schools(cidade, uf);

ALTER TABLE school_users ADD COLUMN birth_date DATE;
ALTER TABLE school_users ADD COLUMN profile_photo BYTEA;

CREATE TABLE registration_requests (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 version BIGINT NOT NULL DEFAULT 0,
 full_name VARCHAR(100) NOT NULL,
 birth_date DATE,
 ra VARCHAR(50) NOT NULL UNIQUE,
 email VARCHAR(255) NOT NULL UNIQUE,
 password_hash VARCHAR(255),
 role VARCHAR(40) NOT NULL CHECK (role IN ('STUDENT', 'TEACHER', 'PEDAGOGICAL_COORDINATOR')),
 school_id BIGINT NOT NULL REFERENCES schools(id),
 terms_version BIGINT NOT NULL REFERENCES terms_versions(version),
 profile_photo BYTEA,
 status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
 requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
 reviewed_at TIMESTAMP WITH TIME ZONE,
 reviewed_by_id BIGINT REFERENCES school_users(id),
 review_reason VARCHAR(2000),
 user_id BIGINT UNIQUE REFERENCES school_users(id)
);
CREATE INDEX idx_registration_school_status ON registration_requests(school_id, status, role);
