CREATE TABLE user_invitations (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 token_hash VARCHAR(128) NOT NULL UNIQUE,
 email VARCHAR(254) NOT NULL,
 role VARCHAR(40) NOT NULL CHECK (role IN ('TEACHER', 'PEDAGOGICAL_COORDINATOR')),
 school_id BIGINT NOT NULL REFERENCES schools(id),
 invited_by_id BIGINT NOT NULL REFERENCES school_users(id),
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
 used_at TIMESTAMP WITH TIME ZONE,
 verified_at TIMESTAMP WITH TIME ZONE,
 verification_code_hash VARCHAR(255),
 verification_code_expires_at TIMESTAMP WITH TIME ZONE,
 resend_available_at TIMESTAMP WITH TIME ZONE,
 verification_attempts INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX idx_user_invitations_email ON user_invitations(email);