CREATE TABLE classrooms (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE school_users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 full_name VARCHAR(200) NOT NULL,
 ra VARCHAR(50) NOT NULL UNIQUE,
 email VARCHAR(255) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 role VARCHAR(40) NOT NULL CHECK (role IN ('ADMIN','TEACHER','PEDAGOGICAL_COORDINATOR','STUDENT')),
 classroom_id BIGINT REFERENCES classrooms(id),
 CHECK (classroom_id IS NULL OR role = 'STUDENT')
);
CREATE TABLE classroom_teachers (
 classroom_id BIGINT NOT NULL REFERENCES classrooms(id),
 teacher_id BIGINT NOT NULL REFERENCES school_users(id),
 PRIMARY KEY (classroom_id, teacher_id)
);
CREATE INDEX idx_classroom_teachers_teacher ON classroom_teachers(teacher_id);
CREATE INDEX idx_users_classroom ON school_users(classroom_id);
CREATE TABLE subjects (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 classroom_id BIGINT NOT NULL REFERENCES classrooms(id),
 teacher_id BIGINT NOT NULL REFERENCES school_users(id),
 UNIQUE (classroom_id, name),
 FOREIGN KEY (classroom_id, teacher_id) REFERENCES classroom_teachers(classroom_id, teacher_id)
);
